### ISSUE TITLE
TypeError: Cannot call method 'match' of undefined

### ISSUE THREAD

**Issue by Kopertje** [dan335/dominus#205]
I20150714-08:14:38.910(-4)? Sikka: starting with these configurations: {"captcha":{"siteKey":"6LdkcgMTAAAAAJosMQhYSfKeFldhn644i9w9c4Oi","secret":"6LdkcgMTAAAAADftIWaISsvQ7SqIeLqHM3PWu79Q"},"rateLimits":{"perIp":20,"perHuman":20,"perSession":20},"times":{"blockIpFor":120000,"humanLivesUpto":3600000},"onlyForHumans":false}
W20150714-08:14:39.035(-4)? (STDERR)
W20150714-08:14:39.035(-4)? (STDERR) /root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150714-08:14:39.035(-4)? (STDERR)                                            throw(ex);
W20150714-08:14:39.035(-4)? (STDERR)                                                  ^
W20150714-08:14:39.065(-4)? (STDERR) TypeError: Cannot call method 'match' of undefined
W20150714-08:14:39.065(-4)? (STDERR)     at translateUrl (packages/ddp/stream_client_common.js:23:1)
W20150714-08:14:39.065(-4)? (STDERR)     at toWebsocketUrl (packages/ddp/stream_client_common.js:77:1)
W20150714-08:14:39.065(-4)? (STDERR)     at [object Object]._.extend._launchConnection (packages/ddp/stream_client_nodejs.js:134:1)
W20150714-08:14:39.065(-4)? (STDERR)     at new LivedataTest.ClientStream (packages/ddp/stream_client_nodejs.js:28:1)
W20150714-08:14:39.065(-4)? (STDERR)     at new Connection (packages/ddp/livedata_connection.js:52:1)
W20150714-08:14:39.065(-4)? (STDERR)     at Object.DDP.connect (packages/ddp/livedata_connection.js:1620:1)
W20150714-08:14:39.066(-4)? (STDERR)     at app/base/connection.js:1:60
W20150714-08:14:39.066(-4)? (STDERR)     at app/base/connection.js:16:3
W20150714-08:14:39.066(-4)? (STDERR)     at /root/dominus/.meteor/local/build/programs/server/boot.js:222:10
W20150714-08:14:39.066(-4)? (STDERR)     at Array.forEach (native)
W20150714-08:14:39.066(-4)? (STDERR)     at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150714-08:14:39.066(-4)? (STDERR)     at /root/dominus/.meteor/local/build/programs/server/boot.js:117:5

**Comment by tyler-johnson** [comment]
I got this as well. After a lot of muddling, I added `public.baseUrl` to `settings.json` and that seemed to get it launched. Then I ran into a whole mess of other errors. @dan335, can we get a really basic "How to start a Dominus server" documentation?

Seems like there is a lot of necessary configuration for it to launch. For example, the game won't do anything until a proper 'gameStartDate' is added to the settings collection. Is there an easier way to add this other than manually going to the database?

**Comment by dan335** [comment]
When Dominus was only one game running at a time it was easy for anyone to clone it and start it up.  Then I made it so that multiple games can run at the same time and all have the same forum and user profiles.  The baseUrl is for what I call the base app which is https://dominusgame.net.  The games use ddp to connect to it for the forums and user profiles.  The base app isn't open source which makes it hard for people to start up their own game.  I kind of did that on purpose because I want it to be open source but I hate the idea that someone could take all my hard work and spin off their own game.

I'll check to see if there's an easy way to make it run and not error.

**Comment by SirChojin** [comment]
Hey,
will be interested too to run a custom server for testing (and why not contributing?) purpose :)
